version: "3"

services:
  vote:
    image: example-voting-app_vote:latest
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    image: example-voting-app_worker:latest

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  result:
    image: example-voting-app_result:latest
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "8080:80"
      - "5858:5858"

  nginx:
    build: ./nginx
    #volumes:
    #  - ./nginx.conf
    depends_on:
      - vote
    ports:
      - "80:80"
