FROM nginx
#COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./resultapp.com.conf /etc/nginx/conf.d/resultapp.com.conf
COPY ./votingapp.com.conf /etc/nginx/conf.d/votingapp.com.conf
#CMD ["nginx"]
EXPOSE 80
EXPOSE 443
